import Head from './components/Head'
import Script from 'next/script'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  deScription: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
        <Header />

        {children}
        
        <Footer />
        <Script async src="js/jquery-3.3.1.min.js"></Script>
        <Script async src="js/bootstrap.min.js"></Script>
        <Script async src="js/jquery-ui.min.js"></Script>
        <Script async src="js/jquery.countdown.min.js"></Script>
        <Script async src="js/jquery.nice-select.min.js"></Script>
        <Script async src="js/jquery.zoom.min.js"></Script>
        <Script async src="js/jquery.dd.min.js"></Script>
        <Script async src="js/jquery.slicknav.js"></Script>
        <Script async src="js/owl.carousel.min.js"></Script>
        <Script async src="js/main.js"></Script>
      </body>
    </html>
  )
}
